// world root:component/root
export type * as DemoPolyErpTypes100 from './interfaces/demo-poly-erp-types.js'; // import demo:poly-erp/types@1.0.0
export type * as WasiCliEnvironment029 from './interfaces/wasi-cli-environment.js'; // import wasi:cli/environment@0.2.9
export type * as WasiCliExit029 from './interfaces/wasi-cli-exit.js'; // import wasi:cli/exit@0.2.9
export type * as WasiCliStderr0210 from './interfaces/wasi-cli-stderr.js'; // import wasi:cli/stderr@0.2.10
export type * as WasiCliStdin0210 from './interfaces/wasi-cli-stdin.js'; // import wasi:cli/stdin@0.2.10
export type * as WasiCliStdout0210 from './interfaces/wasi-cli-stdout.js'; // import wasi:cli/stdout@0.2.10
export type * as WasiCliTerminalInput0210 from './interfaces/wasi-cli-terminal-input.js'; // import wasi:cli/terminal-input@0.2.10
export type * as WasiCliTerminalOutput0210 from './interfaces/wasi-cli-terminal-output.js'; // import wasi:cli/terminal-output@0.2.10
export type * as WasiCliTerminalStderr0210 from './interfaces/wasi-cli-terminal-stderr.js'; // import wasi:cli/terminal-stderr@0.2.10
export type * as WasiCliTerminalStdin0210 from './interfaces/wasi-cli-terminal-stdin.js'; // import wasi:cli/terminal-stdin@0.2.10
export type * as WasiCliTerminalStdout0210 from './interfaces/wasi-cli-terminal-stdout.js'; // import wasi:cli/terminal-stdout@0.2.10
export type * as WasiClocksMonotonicClock0210 from './interfaces/wasi-clocks-monotonic-clock.js'; // import wasi:clocks/monotonic-clock@0.2.10
export type * as WasiClocksWallClock0210 from './interfaces/wasi-clocks-wall-clock.js'; // import wasi:clocks/wall-clock@0.2.10
export type * as WasiFilesystemPreopens0210 from './interfaces/wasi-filesystem-preopens.js'; // import wasi:filesystem/preopens@0.2.10
export type * as WasiFilesystemTypes0210 from './interfaces/wasi-filesystem-types.js'; // import wasi:filesystem/types@0.2.10
export type * as WasiHttpOutgoingHandler0210 from './interfaces/wasi-http-outgoing-handler.js'; // import wasi:http/outgoing-handler@0.2.10
export type * as WasiHttpTypes0210 from './interfaces/wasi-http-types.js'; // import wasi:http/types@0.2.10
export type * as WasiIoError0210 from './interfaces/wasi-io-error.js'; // import wasi:io/error@0.2.10
export type * as WasiIoPoll0210 from './interfaces/wasi-io-poll.js'; // import wasi:io/poll@0.2.10
export type * as WasiIoStreams0210 from './interfaces/wasi-io-streams.js'; // import wasi:io/streams@0.2.10
export type * as WasiRandomInsecureSeed029 from './interfaces/wasi-random-insecure-seed.js'; // import wasi:random/insecure-seed@0.2.9
export type * as WasiRandomRandom0210 from './interfaces/wasi-random-random.js'; // import wasi:random/random@0.2.10
export type * as WasiSocketsInstanceNetwork024 from './interfaces/wasi-sockets-instance-network.js'; // import wasi:sockets/instance-network@0.2.4
export type * as WasiSocketsIpNameLookup024 from './interfaces/wasi-sockets-ip-name-lookup.js'; // import wasi:sockets/ip-name-lookup@0.2.4
export type * as WasiSocketsNetwork024 from './interfaces/wasi-sockets-network.js'; // import wasi:sockets/network@0.2.4
export type * as WasiSocketsTcpCreateSocket024 from './interfaces/wasi-sockets-tcp-create-socket.js'; // import wasi:sockets/tcp-create-socket@0.2.4
export type * as WasiSocketsTcp024 from './interfaces/wasi-sockets-tcp.js'; // import wasi:sockets/tcp@0.2.4
export type * as WasiSocketsUdpCreateSocket024 from './interfaces/wasi-sockets-udp-create-socket.js'; // import wasi:sockets/udp-create-socket@0.2.4
export type * as WasiSocketsUdp024 from './interfaces/wasi-sockets-udp.js'; // import wasi:sockets/udp@0.2.4
export * as gatewayApi from './interfaces/demo-poly-erp-gateway-api.js'; // export demo:poly-erp/gateway-api@1.0.0
