# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
1. Core Data Types
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class Order:
    id: str
    item_id: str
    quantity: int
    user_id: str

@dataclass
class InventoryUpdate:
    item_id: str
    new_stock: int

@dataclass
class Telemetry:
    """
    Telemetry payload for our frontend observability dashboard
    """
    architecture: str
    throughput_msg_sec: int
    latency_ns: int
    timestamp: int

@dataclass
class FraudResult:
    order_id: str
    is_fraud: bool


