// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod demo {
    pub mod poly_erp {
        /// 1. Core Data Types
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct Order {
                pub id: _rt::String,
                pub item_id: _rt::String,
                pub quantity: u32,
                pub user_id: _rt::String,
            }
            impl ::core::fmt::Debug for Order {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Order")
                        .field("id", &self.id)
                        .field("item-id", &self.item_id)
                        .field("quantity", &self.quantity)
                        .field("user-id", &self.user_id)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct InventoryUpdate {
                pub item_id: _rt::String,
                pub new_stock: u32,
            }
            impl ::core::fmt::Debug for InventoryUpdate {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("InventoryUpdate")
                        .field("item-id", &self.item_id)
                        .field("new-stock", &self.new_stock)
                        .finish()
                }
            }
            /// Telemetry payload for our frontend observability dashboard
            #[derive(Clone)]
            pub struct Telemetry {
                pub architecture: _rt::String,
                pub throughput_msg_sec: u32,
                pub latency_ns: u64,
                pub timestamp: u64,
            }
            impl ::core::fmt::Debug for Telemetry {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Telemetry")
                        .field("architecture", &self.architecture)
                        .field("throughput-msg-sec", &self.throughput_msg_sec)
                        .field("latency-ns", &self.latency_ns)
                        .field("timestamp", &self.timestamp)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct FraudResult {
                pub order_id: _rt::String,
                pub is_fraud: bool,
            }
            impl ::core::fmt::Debug for FraudResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("FraudResult")
                        .field("order-id", &self.order_id)
                        .field("is-fraud", &self.is_fraud)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod demo {
        pub mod poly_erp {
            /// 2. The Rust Interface - Process a batch of orders and return updates
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod inventory {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Order = super::super::super::super::demo::poly_erp::types::Order;
                pub type InventoryUpdate = super::super::super::super::demo::poly_erp::types::InventoryUpdate;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_process_orders_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base10 = arg0;
                    let len10 = arg1;
                    let mut result10 = _rt::Vec::with_capacity(len10);
                    for i in 0..len10 {
                        let base = base10
                            .add(i * (7 * ::core::mem::size_of::<*const u8>()));
                        let e10 = {
                            let l0 = *base.add(0).cast::<*mut u8>();
                            let l1 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len2 = l1;
                            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                            let l3 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>();
                            let l7 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *base
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len9 = l8;
                            let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
                            super::super::super::super::demo::poly_erp::types::Order {
                                id: _rt::string_lift(bytes2),
                                item_id: _rt::string_lift(bytes5),
                                quantity: l6 as u32,
                                user_id: _rt::string_lift(bytes9),
                            }
                        };
                        result10.push(e10);
                    }
                    _rt::cabi_dealloc(
                        base10,
                        len10 * (7 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result11 = T::process_orders(result10);
                    let ptr12 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec15 = result11;
                    let len15 = vec15.len();
                    let layout15 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec15.len() * (3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result15 = if layout15.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout15).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout15);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec15.into_iter().enumerate() {
                        let base = result15
                            .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::demo::poly_erp::types::InventoryUpdate {
                                item_id: item_id13,
                                new_stock: new_stock13,
                            } = e;
                            let vec14 = (item_id13.into_bytes()).into_boxed_slice();
                            let ptr14 = vec14.as_ptr().cast::<u8>();
                            let len14 = vec14.len();
                            ::core::mem::forget(vec14);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len14;
                            *base.add(0).cast::<*mut u8>() = ptr14.cast_mut();
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(new_stock13);
                        }
                    }
                    *ptr12.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len15;
                    *ptr12.add(0).cast::<*mut u8>() = result15;
                    ptr12
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_process_orders<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_stock_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base3 = arg0;
                    let len3 = arg1;
                    let mut result3 = _rt::Vec::with_capacity(len3);
                    for i in 0..len3 {
                        let base = base3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e3 = {
                            let l0 = *base.add(0).cast::<*mut u8>();
                            let l1 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len2 = l1;
                            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
                            _rt::string_lift(bytes2)
                        };
                        result3.push(e3);
                    }
                    _rt::cabi_dealloc(
                        base3,
                        len3 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result4 = T::get_stock(result3);
                    let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec6 = (result4).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr5.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                    ptr5
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_stock<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 4, 4);
                }
                pub trait Guest {
                    /// Process a batch of orders, returns inventory updates
                    fn process_orders(
                        orders: _rt::Vec<Order>,
                    ) -> _rt::Vec<InventoryUpdate>;
                    /// Get current stock levels
                    fn get_stock(item_ids: _rt::Vec<_rt::String>) -> _rt::Vec<u32>;
                }
                #[doc(hidden)]
                macro_rules! __export_demo_poly_erp_inventory_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "demo:poly-erp/inventory@1.0.0#process-orders")] unsafe extern
                        "C" fn export_process_orders(arg0 : * mut u8, arg1 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_process_orders_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_demo:poly-erp/inventory@1.0.0#process-orders")] unsafe
                        extern "C" fn _post_return_process_orders(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_process_orders::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "demo:poly-erp/inventory@1.0.0#get-stock")] unsafe extern "C" fn
                        export_get_stock(arg0 : * mut u8, arg1 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_get_stock_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "cabi_post_demo:poly-erp/inventory@1.0.0#get-stock")] unsafe
                        extern "C" fn _post_return_get_stock(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get_stock::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_demo_poly_erp_inventory_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_inventory_service_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::demo::poly_erp::inventory::__export_demo_poly_erp_inventory_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::demo::poly_erp::inventory);
    };
}
#[doc(inline)]
pub(crate) use __export_inventory_service_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:demo:poly-erp@1.0.0:inventory-service:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 608] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x03\x01A\x02\x01\
A\x06\x01B\x08\x01r\x04\x02ids\x07item-ids\x08quantityy\x07user-ids\x04\0\x05ord\
er\x03\0\0\x01r\x02\x07item-ids\x09new-stocky\x04\0\x10inventory-update\x03\0\x02\
\x01r\x04\x0carchitectures\x12throughput-msg-secy\x0alatency-nsw\x09timestampw\x04\
\0\x09telemetry\x03\0\x04\x01r\x02\x08order-ids\x08is-fraud\x7f\x04\0\x0cfraud-r\
esult\x03\0\x06\x03\0\x19demo:poly-erp/types@1.0.0\x05\0\x02\x03\0\0\x05order\x02\
\x03\0\0\x10inventory-update\x01B\x0c\x02\x03\x02\x01\x01\x04\0\x05order\x03\0\0\
\x02\x03\x02\x01\x02\x04\0\x10inventory-update\x03\0\x02\x01p\x01\x01p\x03\x01@\x01\
\x06orders\x04\0\x05\x04\0\x0eprocess-orders\x01\x06\x01ps\x01py\x01@\x01\x08ite\
m-ids\x07\0\x08\x04\0\x09get-stock\x01\x09\x04\0\x1ddemo:poly-erp/inventory@1.0.\
0\x05\x03\x04\0%demo:poly-erp/inventory-service@1.0.0\x04\0\x0b\x17\x01\0\x11inv\
entory-service\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x07\
0.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
